---
name: 'Tests'
on:
  push:
    branches:
      - 'trunk'
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.golangci.toml'
      - 'CONTRIBUTING.md'
      - 'LICENSE-3rdparty.csv'
      - 'LICENSE.md'
      - 'NOTICE'
      - 'README.md'
      - 'SUPPORT.md'
  pull_request:
    branches:
      - 'trunk'
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.golangci.toml'
      - 'CONTRIBUTING.md'
      - 'LICENSE-3rdparty.csv'
      - 'LICENSE.md'
      - 'NOTICE'
      - 'README.md'
      - 'SUPPORT.md'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        go: ['1.21.x', '1.22.x']
    name: 'Tests'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Setup Go environment'
        uses: 'actions/setup-go@v4'
        with:
          go-version: '${{ matrix.go }}'

      - name: 'Run mock tests'
        run: 'make test'
